name: API CI

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pip dependencies
      run: sudo apt install libxml2-dev libxslt1-dev libpq-dev
    - name: Install pip requirements
      run: |
        python -m pip install --upgrade pip
        pip install lxml==4.6.2 requests==2.22.0
    - name: Run API Test
      run: python -m unittest discover -v -s test/api/
