name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install pip dependencies
      run: sudo apt install libxml2-dev libxslt1-dev libpq-dev
    - name: Install pip requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install coverage package
      run: pip install coverage
    - name: Run Unit Tests
      run: coverage run -m unittest -v
    - name: Upload reports to Codecov
      run: bash <(curl -s https://codecov.io/bash)
